[package]
name = "loco-protocol"
version = "1.1.0"
authors = ["storycraft <storycraft@pancake.sh>"]
license = "MIT"
keywords = ["loco", "protocol"]
readme = "readme.md"
description = "Loco protocol implementation"
repository = "https://github.com/storycraft/loco-protocol-rs/"
edition = "2018"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.1"
openssl = "0.10.30"